### PR TITLE
Foldable instance

### PR DESCRIPTION
**Pull request by marcor2048**
I simply made Set an instance of the Foldable class.

### CODE REVIEW

**Comment by giorgidze** [comment]
Thanks a lot for the pull request, supper busy at the moment, will try to
take a look soon.

Cheers, George

**Comment by giorgidze** [comment]
BTW, do you have a test case showing that it works?

Cheers, George

**Comment by marcor2048** [comment]
I have added a test where I make sure the foldr's from the set-monad and from the foldable instance return the same results. I use the (+) function as a test case.

**Comment by giorgidze** [comment]
Thanks a lot for your patches.

I have pulled in and released the new version.

Cheers, George

**Pull request merged**
